import {Hero} from './hero';

export var HEROES: Hero[] = [
    {"id": "11", 
        "name": "Mr. Nice",  
        "type": "Hero",
        "armourClass": 15,
        "hitPoints":20,
        "maxHitPoints":20,
        "strength": 12,
        "dexterity": 12,
        "reflex": 10,
        "attackSpeed": 5,
        "weaponAttackAccuracy": 3,
        "damageRoll": 6,
        "damageModifier": 2,
        "level":1,
        "experienceIfKilled":0,
        "experience":0
    }
    ,{"id": "12", 
        "name": "Narco",  
        "type": "Hero",
        "armourClass": 15,
        "hitPoints":20,
        "maxHitPoints":20,
        "strength": 10,
        "dexterity": 14,
        "reflex": 12,
        "attackSpeed": 5,
        "weaponAttackAccuracy": 3,
        "damageRoll": 6,
        "damageModifier": 2,
        "level":1,
        "experienceIfKilled":0,
        "experience":0
    }
    ,{"id": "13", 
        "name": "Bombasto",  
        "type": "Hero",
        "armourClass": 15,
        "hitPoints":20,
        "maxHitPoints":20,
        "strength": 15,
        "dexterity": 10,
        "reflex": 10,
        "attackSpeed": 5,
        "weaponAttackAccuracy": 3,
        "damageRoll": 6,
        "damageModifier": 2,
        "level":1,
        "experienceIfKilled":0,
        "experience":0
    }
    ,{"id": "14", 
        "name": "Ms. Sparkle",  
        "type": "Hero",
        "armourClass": 15,
        "hitPoints":16,
        "maxHitPoints":16,
        "strength": 10,
        "dexterity": 16,
        "reflex": 11,
        "attackSpeed": 5,
        "weaponAttackAccuracy": 3,
        "damageRoll": 6,
        "damageModifier": 2,
        "level":1,
        "experienceIfKilled":0,
        "experience":0
    }
    ,{"id": "21", 
        "name": "Test Monster",  
        "type": "Hero",
        "armourClass": 12,
        "hitPoints":10,
        "maxHitPoints":10,
        "strength": 10,
        "dexterity": 16,
        "reflex": 10,
        "attackSpeed": 4,
        "weaponAttackAccuracy": 2,
        "damageRoll": 8,
        "damageModifier": 0,
        "level":1,
        "experienceIfKilled":0,
        "experience":0
    }
    

];
